### ISSUE TITLE
Hint to alteration in the function readHeaderFunctions.R

### ISSUE THREAD

**Issue by vagnerfonseca** [Pisca46/edfReader#1]
Hi,

Congratulations on edfReader project it is magnificent, but I found some problems to open some files in EDF format... hindering the implementation for what I need, I am suggesting below some alterations in the **R/readHeaderFunctions.R** file, I believe that you will leave more generic and complete code.

on **line 100** to fix the timezone for the format: H:M:S
hdr$startTime   <- strptime(readChar(inFile, 16, TRUE), format="%d.%m.%y %H:%M:%S") # start date and time of recording

on **line 168** added a function to rename columns that have the same name.
row.names (hdr$sHeaders) <- make.names(label, unique=TRUE)

**Comment by Pisca46** [comment]
Thanks for commenting
I expect to publish a new version within a week in which I will take your comments into account

**Comment by Pisca46** [comment]
In the mean time, I had a closer look to your suggestions.

With respect to the format: H:M:S.

Please, note that - according to the official EDF specification - the starttime in an EDF file shall have the format ‘hh.mm.ss’.
Nevertheless I have no trouble in supporting some less legal variants. I changed the code as follows:

```
dateTimeSring   <- readChar(inFile, 16, TRUE)
if (substr(dateTimeSring, 11, 11) == ':') {
    substr(dateTimeSring, 11, 11) <- '.'
    substr(dateTimeSring, 14, 14) <- '.'
}
hdr$startTime   <- strptime(dateTimeSring, format="%d.%m.%y %H.%M.%S")      # start date and time of recording
```

With respect to the creation of unique names from non-unique labels.
This has been resolved, albeit different from your suggestion.
For an EDF+ file with 2 annotation signals, the following names created: EDF Annotations-1 and EDF Annotations-2.
Making both names different from the non-unique label, prevents some ambiguities when using the signal parameter in readEdfSignals

The new version has been uploaded to GitHub.

I hope I have solved your problems. If not, let me know.
