### ISSUE TITLE
Plotting the signal

### ISSUE THREAD

**Issue by erykwalczak** [Pisca46/edfReader#2]
Hi,

Thanks for the package. I was looking for a long time for a package that can read bdf files. It's high time to ditch EEGLab.
I was wondering how can I plot the signal extracted with this package. Is it possible to add it to the vignette?

**Comment by Pisca46** [comment]
Hi,

I am glad that you appreciate my package,

However, I not sure I understand your question.

edfReader was written to import the date in E/BDF(+) files into an R environment,
Analysing, plotting etc. can be done with all kind of other packages published in the CRAN.

For plotting, there several plot packages (incl tutorials) available, notably:
    - the ‘plot’ package included in the base installation
    - the ‘lattice' package
    - the GGPlot2 package  (Probably the most popular)

What also might help is a package as Seewave. 
By heart, this may require a conversion of a signal to a wav object.
Such a conversion can be quite easily acomplished with tuneR (or maybe also with audio)

Best regards.

**Comment by erykwalczak** [comment]
I realise that edfReader is not a plotting package but that was not what I wanted to ask. Sorry if I didn't make myself clear.

I find the structure of edf/bdf files confusing (not the fault of this package) so I was wondering whether there was a chance for a brief note in the vignette about plotting the signal given the imported edf/bdf data. I believe it would help users (including me) of this package to work with edf/bdf files within R.

**Comment by Pisca46** [comment]
Dear erzk,

About an half hour ago I uploaded a new version with only a new vignette.
This vignette contains, as an example a ggplot2 plot function.

Best regards.
Pisca46

**Comment by erykwalczak** [comment]
Thanks for expanding the vignette. It's very useful.
